; PlatformIO Project Configuration File
; Raket Sistemi — 2 Bolme: BB Payload + CC Drone

[platformio]
default_envs = teensy41_drone

[env:teensy41_payload]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
upload_protocol = teensy-cli
build_flags = -D DEVICE_TYPE=2

[env:teensy41_drone]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
upload_protocol = teensy-cli
build_flags = -D DEVICE_TYPE=3