; PlatformIO Project Configuration File
; Raket Sistemi — Tek cihaz: CC Drone

[env:teensy41_drone]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200

lib_deps = 
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BNO055
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit AHTX0