; PlatformIO Project Configuration File
; Raket Sistemi — Tek cihaz: CC Drone

[platformio]
default_envs = teensy41_drone

[env:teensy41_drone]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
upload_protocol = teensy-cli
lib_deps = 
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit BNO055
    adafruit/Adafruit BusIO
